### ISSUE TITLE
Create, upload and reference favicon

### ISSUE THREAD

**Issue by leeenglestone** [leeenglestone/CodeReviewChecklist#19]

**Comment by JamesLedger** [comment]
I've implemented a temporary favicon from the [material design specs](https://material.io/resources/icons/?icon=check_box&style=baseline) , what do you think?

**Comment by leeenglestone** [comment]
Hi @JamesLedger Looks good.
I think a lot of user agents look for favicons at the root of the site by default. Can you move the favicon.ico to the root of the site and update the reference?

**Comment by JamesLedger** [comment]
Ahh I didn't know that! Sure thing I'll sort that

**Comment by JamesLedger** [comment]
Resolved
