### ISSUE TITLE
Remove the duplicated .gitignore file

### ISSUE THREAD

**Issue by seanstride** [leeenglestone/CodeReviewChecklist#24]
There are 2 .gitignore versions within this repository. There is a version in the root of the repository which is the usual place for it to live and then there is a second version of the same .gitignore within the CodeReviewChecklist.Solution directory. The task here is to remove the .gitignore file that lives within the CodeReviewChecklist.Solution directory

**Comment by leeenglestone** [comment]
Thanks. I didn't even spot this.
