### ISSUE TITLE
Fix invalid HTML  (div inside label)

### ISSUE THREAD

**Issue by leeenglestone** [leeenglestone/CodeReviewChecklist#27]
![image](https://user-images.githubusercontent.com/2360725/88590011-f1731180-d051-11ea-8807-2eea81011727.png)

![image](https://user-images.githubusercontent.com/2360725/88590055-02238780-d052-11ea-8340-1f20b6bbc5cb.png)

**Comment by leeenglestone** [comment]
@JamesLedger Whenever you get around to it, can you look at this one.
It doesn't like the div element you put inside a label element

**Comment by JamesLedger** [comment]
I'll take a look at that now 👍

**Comment by JamesLedger** [comment]
Resolved
