### ISSUE TITLE
Move dark theme toggle to top right of mobile layout

### ISSUE THREAD

**Issue by leeenglestone** [leeenglestone/CodeReviewChecklist#31]
Currently on mobile layout, the dark theme toggle appears underneath the heading.

![image](https://user-images.githubusercontent.com/2360725/88710536-b71b7a00-d10e-11ea-88e8-a201fb7c3e7f.png)

It would look better in the top right

**Comment by Finbob12** [comment]
Hey, Can I please take this one?

**Comment by leeenglestone** [comment]
> Hey, Can I please take this one?

I've assigned it to you @Finbob12 . Good luck! and thanks

-- Lee
