### ISSUE TITLE
Style checklist items with strikethrough when ticked

### ISSUE THREAD

**Issue by leeenglestone** [leeenglestone/CodeReviewChecklist#36]

**Comment by seanstride** [comment]
I'll take a look at this issue @leeenglestone if you can assign it to me please

**Comment by leeenglestone** [comment]
Done (assigned to you @seanstride )

**Comment by seanstride** [comment]
I have created a pull request for this issue when you get chance to look at it @leeenglestone

**Comment by leeenglestone** [comment]
Fab will have a look later!

**Comment by leeenglestone** [comment]
Looks good. Will publish later.

**Comment by leeenglestone** [comment]
Looks good. Now live @seanstride 

closing issue
