### ISSUE TITLE
Menu hamburger no longer visible on small screen sizes

### ISSUE THREAD

**Issue by leeenglestone** [leeenglestone/CodeReviewChecklist#38]
So you can actually click it to expand the menu items, you just can't see it

![image](https://user-images.githubusercontent.com/2360725/89566717-7ca19380-d818-11ea-8197-653fd08172a3.jpeg)

**Comment by leeenglestone** [comment]
@JamesLedger @seanstride

**Comment by leeenglestone** [comment]
Have you seen this @JamesLedger ?

**Comment by JamesLedger** [comment]
Ah apologies meant to say - I've been away camping for a bit. I'll be back late Monday so will take a look Tuesday

**Comment by leeenglestone** [comment]
Cheers @JamesLedger. No rush

**Comment by InocentumAbhijit** [comment]
Please consider checking my PR #40

**Comment by leeenglestone** [comment]
@InocentumAbhijit There was another recent PR done to put the theme toggle in the top right.
Does your branch accommodate for this as you are putting the menu back in the top right?

**Comment by InocentumAbhijit** [comment]
![image](https://user-images.githubusercontent.com/57581122/95503180-9900ae80-09c8-11eb-8f23-03bfb91beb3b.png)
![image](https://user-images.githubusercontent.com/57581122/95503214-addd4200-09c8-11eb-98f3-dfd0e66eba66.png)


Here is what I have done

Do you want to change anything here ?

**Comment by leeenglestone** [comment]
Looks good. @InocentumAbhijit .

Would you mind trying to swap the menu and theme toggle around?
So menu is at the top right?

That would be appreciated.

-- Lee

**Comment by InocentumAbhijit** [comment]
![image](https://user-images.githubusercontent.com/57581122/95864562-29e9d800-0d83-11eb-88cf-bb48cc38778a.png)
![image](https://user-images.githubusercontent.com/57581122/95864568-2ce4c880-0d83-11eb-8dbe-863df64386bd.png)

New implementation

**Comment by leeenglestone** [comment]
Hi @InocentumAbhijit I'm not seeing the hamburger menu on local chrome or safari. Can check you've committed all your changes?

**Comment by InocentumAbhijit** [comment]
Hi, I just have updated the site.css file inside wwwroot/css folder and have not touched any other file. I think there might be a css override after building and running the application. Actually I do not have much knowledge about .NET building process.


Okay, I find out the issue, fixing that with a new commit. The issue is with a comment that I did in site.css file, sorry for that.

Done #42
