### ISSUE TITLE
About page needs updating with additional collaborator(s) details

### ISSUE THREAD

**Issue by leeenglestone** [leeenglestone/CodeReviewChecklist#4]

**Comment by leeenglestone** [comment]
@JamesLedger @sstride i'm happy for you to add your bio onto this page if you are helping with the project

**Comment by JamesLedger** [comment]
Added a little bit about me 😊

**Comment by leeenglestone** [comment]
Looks good @JamesLedger

**Comment by leeenglestone** [comment]
@seanstride Do you want to add a bio section to this page?

**Comment by seanstride** [comment]
@leeenglestone, I'm hoping to get round to adding this at some point tomorrow afternoon all being well

**Comment by seanstride** [comment]
@leeenglestone, I have submitted a pull request for this issue
