### ISSUE TITLE
Dark theme option/make switchable. Dark by default?

### ISSUE THREAD

**Issue by leeenglestone** [leeenglestone/CodeReviewChecklist#8]

**Comment by JamesLedger** [comment]
I'll take care of this, I do like a little bit of designing. Will use Coolors to find a suitable dark mode colour scheme

**Comment by leeenglestone** [comment]
Any luck with this so far @JamesLedger ? This will probably need to be the next issue that needs looking at.

**Comment by JamesLedger** [comment]
Yep I've almost sorted it - will push it to git later on today 👍

**Comment by leeenglestone** [comment]
I'm going to close this issue now @JamesLedger though I imagine we may be raising another one to make the dark theme the default theme. It is so good!
